# frozen_string_literal: true

require 'base64'
require_relative 'assets'

# 16x16 ドット絵を SVG data URI として CSS に注入する。
# 各エンティティ <div> はサイズ系クラス（.b, .z 等）と sprite クラス（.sp-xxx）を持ち、
# 内側テキストを持たない（DOM diff の負荷を最小化）。
#
# - 描画体系：背景画像（SVG data URI）+ image-rendering: pixelated
# - 自弾（shot）のみ プレイヤー色を反映するため CSS mask + currentColor
module Sprites
  module_function

  PALETTE = {
    'Y' => '#ffd54f', 'y' => '#ffeb99', 'g' => '#cc9900', 'G' => '#ffd700',
    'W' => '#ffffff', 'K' => '#1a1a2e', 'd' => '#2a1a3a',
    'P' => '#b388ff', 'p' => '#7e57c2', 'i' => '#e0bbff',
    'R' => '#ff5e7e', 'r' => '#c2185b', 'q' => '#ff9eb5',
    'B' => '#80d8ff', 'b' => '#0288d1', 'c' => '#bbeeff',
    'O' => '#ff9933', 'o' => '#cc6622', 'a' => '#ffcc88',
    'M' => '#ffcc00', 'm' => '#ff6633',
    'L' => '#ffe5dd', 'l' => '#ff7766', 'x' => '#aa3344',
    'F' => '#deb887', 'f' => '#8b4513', 'e' => '#ffe9cc',
    'D' => '#cc3344', 'C' => '#ffe066', 'n' => '#88aa44'
  }.freeze

  # ── 16x16 ドット絵カタログ ──
  # '.' = 透明、その他は PALETTE のキー。インデント注意（ヒアドキュメント）。
  ART = {
    player: <<~ART,
      ................
      ................
      .......YY.......
      .......YY.......
      ......YyyY......
      ......YyyY......
      .YY.YYYWWYYY.YY.
      .YYYYYYWWYYYYYY.
      ..YYYYYyyYYYYY..
      ...YYYYYYYYYY...
      ....YYYYYYYY....
      ....YY....YY....
      ...YY......YY...
      ..YY........YY..
      ................
      ................
    ART

    # currentColor で塗られるシルエット（W が描画される画素）
    shot: <<~ART,
      ................
      ................
      ................
      .......WW.......
      ......WWWW......
      .....WWWWWW.....
      ...WWWWWWWWWW...
      ..WWWWWWWWWWWW..
      ..WWWWWWWWWWWW..
      ...WWWWWWWWWW...
      .....WWWWWW.....
      ......WWWW......
      .......WW.......
      ................
      ................
      ................
    ART

    zako_octopus: <<~ART,
      ................
      ....pPPPPPPp....
      ...PPPPPPPPPP...
      ..PPpPPPPPPpPP..
      ..PWKpPPPPpKWP..
      ..PWKPPPPPPKWP..
      ..PPPPPpPpPPPP..
      ..PPPPpPPpPPPP..
      ..PPPPPPPPPPPP..
      ..pPpPpPpPpPpP..
      .pP.pP.PpP.Pp...
      .p..P..p.P..p...
      .p..p..p.p..p...
      ................
      ................
      ................
    ART

    zako_pufferfish: <<~ART,
      .......oo.......
      .....o.OO.o.....
      ....oOOOOOOo....
      ...OOOOOOOOO....
      ..OOOOOOOOOOOO..
      .O.OOWKOOWKO.O..
      .OOOOWKOOWKOOOO.
      OOOOOOOaaOOOOOOO
      OOOOOaaaaaOOOOOO
      .OOOOOOaaOOOOOO.
      .O.OOOOOOOOOO.O.
      ..OOOOOOOOOOOO..
      ...OOOOOOOOOO...
      ....oOOOOOOOo...
      .....o.OO.o.....
      .......oo.......
    ART

    zako_shrimp: <<~ART,
      ................
      ................
      ................
      ...rrrr.........
      ..RRRRRR........
      .RRRRRRRRR......
      RRRRWKRRRRR.....
      RRRWKKRRRRRR....
      .RRRRRRRRRRRR...
      .RRRRRRRRRRRRR..
      ..RRRRRRRRRRRRR.
      ...RRRRRRRRRRRR.
      ....rrrrrrrrrrr.
      .....r.r.r.r.r..
      ................
      ................
    ART

    boss_body: <<~ART,
      ....pPPPPPPPp...
      ...PPPPPPPPPPP..
      ..PPPPPPPPPPPPP.
      .PPPPPPPPPPPPPP.
      .PpPiPPPPPPiPpp.
      .PpPWKKPPWKKWpp.
      .PpPWKKPPWKKWpp.
      .PPPPPPiiPPPPPP.
      .PPPPPPPPPPPPPP.
      .PPPPpPPPPpPPPP.
      .pPPPPpPPpPPPPp.
      .pPpPpPpPpPpPpp.
      pp.pP.PpPp.Pp.pp
      p..p..p..p..p..p
      ................
      ................
    ART

    boss_crown: <<~ART,
      ................
      ................
      .GG..GG..GG..GG.
      .GG..GG..GG..GG.
      .GGGGGGGGGGGGGG.
      .GGGGGRRGGRRGGGG
      .GgGgGgGgGgGgGgg
      .ggggggggggggggg
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................
    ART

    bullet_normal: <<~ART,
      ................
      ................
      ................
      .....BBBBBB.....
      ....BcBBBBcB....
      ...BcWWBBBBBb...
      ...BWWBBBBBBb...
      ...BBBBBBBBBb...
      ...BBBBBBBBBb...
      ....BbbbbbbB....
      .....bbbbbb.....
      ................
      ................
      ................
      ................
      ................
    ART

    # 5 角星（ボスの星形バースト弾）。輪郭は黄、上下のトゲ先端を白で光らせる。
    bullet_star: <<~ART,
      ................
      ................
      .......YY.......
      ......YyyY......
      .YYY..YYYY..YYY.
      ..YYYYYYYYYYYY..
      ...YYYYyyYYYY...
      ....YYYyyYYY....
      .....YYyyYY.....
      ....YYYyyYYY....
      ....YYY..YYY....
      ...YY......YY...
      ..YY........YY..
      .YY..........YY.
      ................
      ................
    ART

    # 雪結晶（送られてきたお邪魔弾）。8 方向対称・タップした両先端は淡シアンで凍り感。
    bullet_garbage: <<~ART,
      ......cWWc......
      .......WW.......
      W......WW......W
      WW.....WW.....WW
      .WW....WW....WW.
      ..WW...WW...WW..
      ...WW..WW..WW...
      ccWWWWWWWWWWWWcc
      ccWWWWWWWWWWWWcc
      ...WW..WW..WW...
      ..WW...WW...WW..
      .WW....WW....WW.
      WW.....WW.....WW
      W......WW......W
      .......WW.......
      ......cWWc......
    ART

    warning: <<~ART,
      ................
      ................
      .......MM.......
      ......MMMM......
      ......MMMM......
      .....MMKKMM.....
      .....MMKKMM.....
      ....MMMKKMMM....
      ....MMMKKMMM....
      ...MMMMKKMMMM...
      ...MMMMKKMMMM...
      ..MMMMMMMMMMMM..
      ..MMMMMKKMMMMM..
      .MMMMMMMMMMMMMM.
      .mmmmmmmmmmmmmm.
      ................
    ART

    food_squid: <<~ART,
      ................
      ....iPPPPPPi....
      ...PPPPPPPPPP...
      ..PiPPPPPPPPiP..
      ..PWKPPPPPPKWP..
      ..PWKPPPPPPKWP..
      ..PPPPPRRPPPPP..
      ..PPPPPPPPPPPP..
      ..PPPPPPPPPPPP..
      ..pPpPpPpPpPpP..
      ..p.pP.pP.Pp.p..
      ..p..p..p..p....
      ................
      ................
      ................
      ................
    ART

    food_ramen: <<~ART,
      ................
      .nnnnnnnnnnnnnn.
      n..............n
      n.WWWWWWWWWWWW.n
      n.WCCCCCCCCCCW.n
      n.WCWCWCWCWCWW.n
      n.WCCOCCOCCOWW.n
      n.WCOOOOOOOWWW.n
      n.WCCOOOOCCWWW.n
      n.WCCCOOOCCCWW.n
      n.WWCCCCCCCCWW.n
      .OWWWWWWWWWWWWO.
      .OOOOOOOOOOOOOO.
      ..oOOOOOOOOOOo..
      ...oooooooooo...
      ................
    ART

    food_sushi: <<~ART,
      ................
      ................
      ................
      ...llllllllll...
      ..llxxllllxxll..
      .llllllllllllll.
      .llllllllllllll.
      .lxllllllllllxl.
      .LLLLLLLLLLLLLL.
      .LWWLLLLLLLWWLL.
      .LLLLLLLLLLLLLL.
      .LLLLLLLLLLLLLL.
      .LLLLLLLLLLLLLL.
      ..LLLLLLLLLLLL..
      ................
      ................
    ART

    food_burger: <<~ART,
      ................
      ....FFFFFFFF....
      ...FFFFFFFFFF...
      ..FeFFWFFWFFFF..
      ..FFFFFFFFFFFF..
      .FFFFFFFFFFFFFF.
      .nnnnnnnnnnnnnn.
      .ffffffffffffff.
      .OOOOOOOOOOOOOO.
      .ffffffffffffff.
      .FFFFFFFFFFFFFF.
      ..FFFFFFFFFFFF..
      ...FFFFFFFFFF...
      ....FFFFFFFF....
      ................
      ................
    ART

    food_bento: <<~ART,
      ................
      .DDDDDDDDDDDDDD.
      D..............D
      D.LLLLLLLLLLLL.D
      D.LCLCLCLCLCLL.D
      D.LCCCCCCCCCLL.D
      D.LLLLLLLLLLLL.D
      D.OO.OO.OO.OO..D
      D.OOOOOOOOOOOO.D
      D.LLLLLLLLLLLL.D
      D.LCLCLCLCLCLL.D
      D.LLLLLLLLLLLL.D
      D..............D
      .dddddddddddddd.
      ................
      ................
    ART
  }.freeze

  # 雑魚・食べ物の emoji（既存データ）から sprite 名への lookup
  ZAKO_SPRITES = {
    Assets::Icons::ZAKO_BASIC => :zako_octopus,
    Assets::Icons::ZAKO_TANK  => :zako_pufferfish,
    Assets::Icons::ZAKO_AGILE => :zako_shrimp
  }.freeze

  FOOD_SPRITES = {
    Assets::Icons::FOOD_SQUID  => :food_squid,
    Assets::Icons::FOOD_RAMEN  => :food_ramen,
    Assets::Icons::FOOD_SUSHI  => :food_sushi,
    Assets::Icons::FOOD_BURGER => :food_burger,
    Assets::Icons::FOOD_BENTO  => :food_bento
  }.freeze

  def class_name(sprite_name)
    "sp-#{sprite_name}"
  end

  # 全 sprite を CSS 規則として出力（STATIC_CSS に1度だけ埋め込まれる）。
  # shot だけは mask 方式（プレイヤー色を currentColor で反映）。
  def all_css
    rules = ART.keys.map do |name|
      uri = data_uri(name)
      if name == :shot
        ".#{class_name(name)} { -webkit-mask:url(\"#{uri}\") center/contain no-repeat;mask:url(\"#{uri}\") center/contain no-repeat;background-color:currentColor; }"
      else
        ".#{class_name(name)} { background:url(\"#{uri}\") center/contain no-repeat; }"
      end
    end
    rules.join("\n")
  end

  # data URI は base64 で固定する。
  # CGI.escape は空白を `+` にする form encoding (RFC 1738) なので、
  # SVG の `<svg xmlns="...">` の空白が `+` になりブラウザが `<svg+xmlns="...">`
  # と解釈して画像が壊れる。base64 ならエンコード後文字は [A-Za-z0-9+/=] に限られ
  # CSS / data URI どちらの文脈でも安全。
  def data_uri(sprite_name)
    @cache ||= {}
    @cache[sprite_name] ||= "data:image/svg+xml;base64,#{Base64.strict_encode64(svg(ART.fetch(sprite_name)))}"
  end

  # ART テキスト → SVG。横方向に同色を連結して rect 数を抑える（RLE）。
  def svg(art_text)
    lines = art_text.lines.map(&:chomp).reject(&:empty?)
    h = lines.size
    w = lines.first.length
    rects = []
    lines.each_with_index do |line, y|
      x = 0
      while x < line.length
        c = line[x]
        if c == '.'
          x += 1
          next
        end
        run = 1
        run += 1 while x + run < line.length && line[x + run] == c
        color = PALETTE.fetch(c)
        rects << %(<rect x="#{x}" y="#{y}" width="#{run}" height="1" fill="#{color}"/>)
        x += run
      end
    end
    %(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 #{w} #{h}" shape-rendering="crispEdges">#{rects.join}</svg>)
  end
end
